### ISSUE TITLE
Please support wrapping ANSI escape sequences in PS1

### ISSUE THREAD

**Issue by joshtriplett** [JoshMcguigan/libps1#3]
The issue at https://github.com/NerdyPepper/pista/issues/3 , referenced in the source, occurs because the ANSI color sequences take up zero width, and readline/bash expect them to take up width. bash has a method of dealing with this: if you surround all the ANSI color sequences (but not any printing characters) in `\[` and `\]`, bash will assume they take up zero width. libps1 could support emitting these sequences in the output. `ansi_term` does support this: instead of calling `paint`, print `\[`, then `some_style.prefix()`, then `\]`, then the text, then `\[`, then `some_style.suffix()`, then `\]`.

**Comment by JoshMcguigan** [comment]
Closed in #6
